# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: fcf056a3a9106a0ab97159604147fc27219006c22db79660e2bb271eb03fa45e90e4676fbddcc70091e1143c7627b1ccbf240df5f01a97ca8c3e5a15ca9c4d2c

test:
  secret_key_base: 0e6d1b6c02246a7b364380ffb8f1470d7a91ae1be6a04d547921c4320c3066866c1966b6173e9fa88eb6f5d2824b1990114289ba29e3e4a1c9efff8b14baa5e6

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
